apiVersion: apps/v1
kind: Deployment
metadata:
  name: wlp
  labels:
    app: wlp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: wlp
  template:
    metadata:
      labels:
        app: wlp
    spec:
      containers:
      - name: wlp
        image: websphere-liberty
        ports:
        - containerPort: 9080
        - containerPort: 9443